services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - api
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    depends_on:
      - api
      - web
    ports:
      - "80:80"
    restart: unless-stopped
