version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env.example
    networks: [app]

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env.example
    networks: [app]

  nginx:
    build: ./nginx
    depends_on:
      - api
      - web
    ports:
      - "80:80"
    networks: [app]

networks:
  app:
    name: skeleton_prod_net
